name: ${project.name}
main: ${project.groupId}.${project.artifactId}.EventHelper
version: ${project.version}
description: ${project.description}
softdepend: [Vault]
depend: [WorldEdit]

commands:
    eventhelper:
        description: The base command for all Event Helper commands
        permissions: eh.commands.eventhelper
        usage: /eventhelper [set]
        aliases: [eh,eventh,ehelper]

permissions:
    eh.commands.eventhelper.*:
        description: Allows use of all Event Helper commands
        default: op
        children:
            eh.commands.set: true
            eh.commands.get: true
            eh.commands.sudo: true
            eh.commands.reload: true
    eh.commands.set:
       description: Allows setting of event parameters
       default: op
    eh.commands.get:
       description: Allows getting of event parameters
       default: op
    eh.commands.sudo:
       description: Allows sudoing of another user
       default: op
    eh.commands.reload:
       description: Allows reloading of the config file
       default: op